use std::fs::File;
use std::io::Write;
use rand::Rng;

fn main() {

    let mut key = [0u8; 32];
    rand::thread_rng().fill(&mut key);

    let key_code = format!(
        "pub const SECRET_KEY: [u8; 32] = [{}];",
        key.iter().map(|byte| format!("0x{:02x}", byte)).collect::<Vec<String>>().join(", ")
    );


    let mut file = File::create("src/constant.rs").expect("Failed to create constant.rs file");
    writeln!(file, "// This file is autogenerated during build\n{}", key_code).expect("Failed to write to constant.rs file");
}
