name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x86_64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.69

      - name: Install cross
        run: cargo install cross

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cargo build --target ${{ matrix.arch }}-unknown-linux-gnu --release
          else
            cargo build --target ${{ matrix.arch }}-pc-windows-msvc --release
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            target/x86_64-unknown-linux-gnu/release/your_project
            target/x86_64-pc-windows-msvc/release/your_project.exe
