name: Build

on:
  push:
    branches:
      - ['master']
  pull_request:
    branches:
      - ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x86_64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.69

      - name: Install cross
        run: cargo install cross

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cross build --target ${{ matrix.arch }}-unknown-linux-gnu --release
          else
            cross build --target ${{ matrix.arch }}-pc-windows-msvc --release
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: target/${{ matrix.arch }}-unknown-linux-gnu/release/owlnigma
          path: target/${{ matrix.arch }}-pc-windows-msvc/release/owlnigma.exe
